name: lecture_hack
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  permission_handler: ^12.0.1
  record: ^6.2.0
  path_provider: ^2.1.5
  google_generative_ai: ^0.4.7
  http: ^1.6.0
  audioplayers: ^6.6.0
  shared_preferences: ^2.5.5
  flutter_markdown: ^0.7.7+1
  share_plus: ^12.0.2
  google_fonts: ^8.0.2
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.13
  isar_generator: ^3.1.0+1
  # 👇 アプリアイコン自動生成パッケージを追加！
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

# 👇 ここから下がアプリアイコンの設定です！
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 21